### ISSUE TITLE
Crashes on some songs

### ISSUE THREAD

**Issue by anotheredward** [96AA48/yplayer#4]
When trying to play song 0 from the search "oakland daniela" I get the following error

```
could not extract html5player key: //s.ytimg.com/yts/jsbin/player-en_US-vflJENbn4/base.js
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: Could not extract signature deciphering actions
    at /Users/ed/.nvm/versions/node/v4.2.1/lib/node_modules/yplayer/node_modules/ytdl-core/lib/sig.js:49:13
    at IncomingMessage.<anonymous> (/Users/ed/.nvm/versions/node/v4.2.1/lib/node_modules/yplayer/node_modules/ytdl-core/lib/request.js:34:9)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:903:12)
    at doNTCallback2 (node.js:439:9)
    at process._tickCallback (node.js:353:17)
```

**Comment by 96AA48** [comment]
I can recreate the issue and I'll be looking into it.

**Comment by 96AA48** [comment]
It seems that the issue seems to be around VEVO videos as far as I can tell. I have no idea how to fix this issue however. You're probably better off reporting this upstream to node-ytdl-core.
