### ISSUE TITLE
Can't play any music

### ISSUE THREAD

**Issue by kiuKisas** [96AA48/yplayer#7]
Hi,
Every time I try to start a music after searching for it, I got this:

```
could not extract html5player key: //s.ytimg.com/yts/jsbin/player-en_US-vflkqCvzc/base.js
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Could not extract signature deciphering actions
    at /usr/lib/node_modules/yplayer/node_modules/ytdl-core/lib/sig.js:49:13
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/yplayer/node_modules/ytdl-core/lib/request.js:34:9)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by 96AA48** [comment]
Hey @kiuKisas,
Thanks for reporting this issue. This issue has to do with some backend stuff concerning `youtube-crawler` another package that I made. I'll be sure to look into this issue when I have the time!

**Comment by 96AA48** [comment]
Hey @kiuKisas I finally had some time into the issue that you found. I updated the depency for ytdl-core. This issue should be resolved now. I will patch yplayer and push the new release soon.

Thanks for reporting!
